<form name="test-form" id="subscription-form" action="subscription" method="post">
<p><label for="name">Name <span class="required">*</span></label></p>
<p><input id="name" name="name" class="input-text required-entry" /></p>
<p><label for="useremail">Email <span class="required">*</span></label></p>
<p><input type="text" name="useremail" id="useremail" class="input-text required-entry validate-email" /></p>
<p><label for="phone">Phone</label></p>
<p><input id="phone" name="phone" class="input-text validate-phoneStrict" /></p>
<p><label for="message">Message <span class="required">*</span></label></p>
<p><textarea id="message" name="message" rows=5 cols=45 class="input-text required-entry" /></textarea></p>
<p><input type="submit" name="submit" value="Submit" /></p>
</form>

